version: "3.9"
services:
  api:
    build: ./services/api
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [postgres, minio, rag, renderer]
  orchestrator:
    build: ./services/orchestrator
    env_file: .env
    depends_on: [api]
  rules:
    build: ./services/rules
  semantic:
    build: ./services/semantic
  rag:
    build: ./services/rag
    env_file: .env
    ports: ["8300:8300"]
    depends_on: [postgres]
  renderer:
    build: ./services/renderer
    ports: ["8400:8400"]
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: clausematch
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio:/data"]
volumes:
  pgdata:
  minio:
